theme: minima
title: Ana Sophia's Professional Portfolio
description: Hello, I'm Ana Sophia Lozano, a Data Analyst from Nevada. I am currently working on earning my Google Data Analytics Certificate. This is where I will be posting my fufture products. 
